=== AngeloTrifelli/Tesina-LWEB/XML/Attivita.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaAttivita">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="attivita" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="attivita">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="descrizione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="linkImmagine" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="oraApertura" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="oraChiusura" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="prezzoOrario" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="listaPrenotazioni" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nome" type="xsd:ID" />
    <xsd:element name="descrizione" type="xsd:string" />
    <xsd:element name="linkImmagine" type="xsd:string" />
    <xsd:element name="oraApertura" type="xsd:time" />
    <xsd:element name="oraChiusura" type="xsd:time" />
    <xsd:element name="prezzoOrario">
        <xsd:simpleType>
            <xsd:restriction base="xsd:double">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="listaPrenotazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prenotazione" minOccurs="0" maxOccurs="unbounded" /> 
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prenotazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="idPrenotazione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="codFisc" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="data" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="oraInizio" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="oraFine" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="prezzoTotale" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="creditiUsati" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="idPrenotazione" type="xsd:ID" />
    <xsd:element name="codFisc" type="xsd:string" />
    <xsd:element name="data" type="xsd:date" />
    <xsd:element name="oraInizio" type="xsd:time" />
    <xsd:element name="oraFine" type="xsd:time" />
    <xsd:element name="prezzoTotale">
        <xsd:simpleType>
            <xsd:restriction base="xsd:double">
                <xsd:minExclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="creditiUsati">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
</xsd:schema>

=== AngeloTrifelli/Tesina-LWEB/XML/Attivita.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaAttivita xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Attivita.xsd">
  <attivita id="A1">
    <nome>Palestra</nome>
    <descrizione>Ubicata all'interno dell'hotel ed equipaggiata con le ultime macchine di Technogym, una palestra interna rappresentala soluzione perfetta per mantenersi in forma anche se lontani da casa. Hotel Sapienza vi propone una palestra dotata di:<![CDATA[<br />]]>Tapis roulant e cyclette<![CDATA[<br />]]>Materassini e ball per aerobica e pilates<![CDATA[<br />]]>Pesie bilancieri di varie dimensioni<![CDATA[<br />]]>. Vengono inoltre messi a disposizione gli spogliatoi dotati di armadiettie docce.</descrizione>
    <linkImmagine>https://www.destinazioneavventura.it/wp-content/uploads/2019/01/Excelsior-Sport-Hotel-Gala-Milano-Vacanza-Sportive.jpg</linkImmagine>
    <oraApertura>06:00:00</oraApertura>
    <oraChiusura>22:00:00</oraChiusura>
    <prezzoOrario>10</prezzoOrario>
    <listaPrenotazioni>
      <prenotazione>
        <idPrenotazione>A1-PA1</idPrenotazione>
        <codFisc>RSSGNN64R03E472G</codFisc>
        <data>2022-10-29</data>
        <oraInizio>17:00:00</oraInizio>
        <oraFine>19:00:00</oraFine>
        <prezzoTotale>20</prezzoTotale>
        <creditiUsati>0</creditiUsati>
      </prenotazione>
      <prenotazione>
        <idPrenotazione>A1-PA2</idPrenotazione>
        <codFisc>RSSGNN64R03E472G</codFisc>
        <data>2022-10-28</data>
        <oraInizio>07:00:00</oraInizio>
        <oraFine>10:00:00</oraFine>
        <prezzoTotale>30</prezzoTotale>
        <creditiUsati>50</creditiUsati>
      </prenotazione>
    </listaPrenotazioni>
  </attivita>
  <attivita id="A2">
    <nome>Spa</nome>
    <descrizione>Nel primo piano dell'hotel potete trovare la nostra spa di ultime generazione, composta da ben 5 piscine di varie dimensioni, alternate da acqua fredda e calda. Centinaia sono ii turisti che ogni anno soggiornano qui unicamente per provare delle giornate di totale benessere e relex. Oltre le 5 picine troverete:<![CDATA[<br />]]>Sauna<![CDATA[<br />]]>Area massaggi<![CDATA[<br />]]>Doccie con scrub e creme per la pelle<![CDATA[<br />]]>. Chiediamo unicamente di portarsi con se ciabatte e accappatoio personale.</descrizione>
    <linkImmagine>https://www.forniturealberghiereonline.it/images/arredamento-spa/allestire-spa-in-hotel.jpg</linkImmagine>
    <oraApertura>10:00:00</oraApertura>
    <oraChiusura>18:00:00</oraChiusura>
    <prezzoOrario>20</prezzoOrario>
    <listaPrenotazioni>
      <prenotazione>
        <idPrenotazione>A2-PA1</idPrenotazione>
        <codFisc>BRSMTT64E05E472K</codFisc>
        <data>2022-12-12</data>
        <oraInizio>10:00:00</oraInizio>
        <oraFine>15:00:00</oraFine>
        <prezzoTotale>100</prezzoTotale>
        <creditiUsati>0</creditiUsati>
      </prenotazione>
    </listaPrenotazioni>
  </attivita>
  <attivita id="A3">
    <nome>Parco</nome>
    <descrizione>Siete una famiglia numerosa? I vostri bambini in vacanza con voi si annoiano? Non è un problema grazie al fantastico parco giochi che Hotel Sapienza mette a disposizione per voi. Portate i vostri bambini a provare:<![CDATA[<br />]]> Le nuove altalene con dispsitivi di sicurezza integrati<![CDATA[<br />]]>I nuovi scivoli d'acqua alti più di 10 metri<![CDATA[<br />]]>I nostri trampolini con rimbalzo controllato<![CDATA[<br />]]>Insomma i vostri bambini non vedranno l'ora di passare del tempo insieme ai nostri tutori presenti durante tutto l'orario di apertura.</descrizione>
    <linkImmagine>https://admin.abc.sm/img/gallery/upload/8507/offerte/crp910x650o5-21986-d4-6309-copia.jpg</linkImmagine>
    <oraApertura>08:00:00</oraApertura>
    <oraChiusura>12:00:00</oraChiusura>
    <prezzoOrario>5</prezzoOrario>
    <listaPrenotazioni>
    </listaPrenotazioni>
  </attivita>
</listaAttivita>
