=== AngeloTrifelli/Tesina-LWEB/XML/Camere.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaCamere">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Camera" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Camera">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tipo" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="prezzo" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="listaPrenotazioni" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="numero" type="xsd:ID" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="tipo">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Standard Singola" />
                <xsd:enumeration value="Standard Doppia" />
                <xsd:enumeration value="Suite" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="prezzo">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:enumeration value="30" />
                <xsd:enumeration value="60" />
                <xsd:enumeration value="150" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="listaPrenotazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prenotazione" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prenotazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="idPrenotazione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="codFisc" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="statoSoggiorno" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="creditiUsati" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="dataArrivo" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="dataPartenza" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="idPrenotazione" type="xsd:ID" />
    <xsd:element name="codFisc" type="xsd:string" />
    <xsd:element name="statoSoggiorno">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Pagamento sospeso" />
                <xsd:enumeration value="Pagamento rifiutato" />
                <xsd:enumeration value="Approvato" />
                <xsd:enumeration value="Terminato" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="creditiUsati">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="dataArrivo" type="xsd:date" />
    <xsd:element name="dataPartenza" type="xsd:date" />
</xsd:schema>

=== AngeloTrifelli/Tesina-LWEB/XML/Camere.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaCamere xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Camere.xsd">
  <Camera numero="C110">
    <tipo>Standard Doppia</tipo>
    <prezzo>60</prezzo>
    <listaPrenotazioni>
      <prenotazione>
        <idPrenotazione>C110-PC1</idPrenotazione>
        <codFisc>RSSGNN64R03E472G</codFisc>
        <statoSoggiorno>Approvato</statoSoggiorno>
        <creditiUsati>0</creditiUsati>
        <dataArrivo>2022-10-28</dataArrivo>
        <dataPartenza>2022-10-31</dataPartenza>
      </prenotazione>
      <prenotazione>
        <idPrenotazione>C110-PC2</idPrenotazione>
        <codFisc>BRSMTT64E05E472K</codFisc>
        <statoSoggiorno>Approvato</statoSoggiorno>
        <creditiUsati>50</creditiUsati>
        <dataArrivo>2022-12-12</dataArrivo>
        <dataPartenza>2022-12-20</dataPartenza>
      </prenotazione>
      <prenotazione>
        <idPrenotazione>C110-PC3</idPrenotazione>
        <codFisc>RSSGNN64R03E472G</codFisc>
        <statoSoggiorno>Terminato</statoSoggiorno>
        <creditiUsati>20</creditiUsati>
        <dataArrivo>2022-07-13</dataArrivo>
        <dataPartenza>2022-07-15</dataPartenza>
      </prenotazione>
      <prenotazione>
        <idPrenotazione>C110-PC4</idPrenotazione>
        <codFisc>CPZGLC90P11H501W</codFisc>
        <statoSoggiorno>Approvato</statoSoggiorno>
        <creditiUsati>0</creditiUsati>
        <dataArrivo>2022-11-11</dataArrivo>
        <dataPartenza>2022-11-13</dataPartenza>
      </prenotazione>
    </listaPrenotazioni>
  </Camera>
  <Camera numero="C200">
    <tipo>Standard Singola</tipo>
    <prezzo>30</prezzo>
    <listaPrenotazioni>
      <prenotazione>
        <idPrenotazione>C200-PC1</idPrenotazione>
        <codFisc>BNCVNT00R67E472F</codFisc>
        <statoSoggiorno>Pagamento sospeso</statoSoggiorno>
        <creditiUsati>0</creditiUsati>
        <dataArrivo>2022-10-28</dataArrivo>
        <dataPartenza>2022-10-30</dataPartenza>
      </prenotazione>
    </listaPrenotazioni>
  </Camera>
  <Camera numero="C300">
    <tipo>Suite</tipo>
    <prezzo>150</prezzo>
    <listaPrenotazioni>
      <prenotazione>
        <idPrenotazione>C300-PC1</idPrenotazione>
        <codFisc>CPZGLC90P11H501W</codFisc>
        <statoSoggiorno>Pagamento rifiutato</statoSoggiorno>
        <creditiUsati>0</creditiUsati>
        <dataArrivo>2022-11-17</dataArrivo>
        <dataPartenza>2022-11-18</dataPartenza>
      </prenotazione>
      <prenotazione>
        <idPrenotazione>C300-PC2</idPrenotazione>
        <codFisc>VRDRRT00L13E472M</codFisc>
        <statoSoggiorno>Terminato</statoSoggiorno>
        <creditiUsati>0</creditiUsati>
        <dataArrivo>2022-09-17</dataArrivo>
        <dataPartenza>2022-09-18</dataPartenza>
      </prenotazione>
    </listaPrenotazioni>
  </Camera>
</listaCamere>
