=== AngeloTrifelli/Tesina-LWEB/XML/Categorie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaCategorie">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="categoria" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="categoria">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="stato" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="listaAzioni" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="listaUtenti" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nome" type="xsd:string" />
    <xsd:element name="stato">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Attiva" />
                <xsd:enumeration value="Disabilitata" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="listaAzioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="azioneUtente" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="listaUtenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="utente" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="azioneUtente">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nomeAzione" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="utente">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="codFisc" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nomeAzione" type="xsd:string" />
    <xsd:element name="codFisc" type="xsd:string" />
</xsd:schema>

=== AngeloTrifelli/Tesina-LWEB/XML/Categorie.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaCategorie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Categorie.xsd">
    <categoria>
        <nome>Stanza</nome>
        <stato>Attiva</stato>
        <listaAzioni>
            <azioneUtente>
                <nomeAzione>Prenotazione soggiorno</nomeAzione>
            </azioneUtente>
        </listaAzioni>        
        <listaUtenti>
            <utente>
                <codFisc>RSSGNN64R03E472G</codFisc>
            </utente>
            <utente>
                <codFisc>VRDRRT00L13E472M</codFisc>
            </utente>
        </listaUtenti>
    </categoria>
    <categoria>
        <nome>Generale</nome>
        <stato>Attiva</stato>
        <listaAzioni>
            <azioneUtente>
                <nomeAzione>Registrazione cliente</nomeAzione>
            </azioneUtente>
        </listaAzioni>        
        <listaUtenti>
            <utente>
                <codFisc>RSSGNN64R03E472G</codFisc>
            </utente>
            <utente>
                <codFisc>VRDRRT00L13E472M</codFisc>
            </utente>
            <utente>
                <codFisc>CPZGLC90P11H501W</codFisc>
            </utente>
            <utente>
                <codFisc>BRSMTT64E05E472K</codFisc>
            </utente>
            <utente>
                <codFisc>BNCVNT00R67E472F</codFisc>
            </utente>
        </listaUtenti>
    </categoria>
    <categoria>
        <nome>Servizi</nome>
        <stato>Attiva</stato>
        <listaAzioni>
            <azioneUtente>
                <nomeAzione>Prenotazione tavolo</nomeAzione>
            </azioneUtente>
            <azioneUtente>
                <nomeAzione>Prenotazione servizio in camera</nomeAzione>
            </azioneUtente>
            <azioneUtente>
                <nomeAzione>Prenotazione attivita</nomeAzione>
            </azioneUtente>
        </listaAzioni>        
        <listaUtenti>
            <utente>
                <codFisc>RSSGNN64R03E472G</codFisc>
            </utente>
            <utente>
                <codFisc>VRDRRT00L13E472M</codFisc>
            </utente>
        </listaUtenti>
    </categoria>
    <categoria>
        <nome>Crediti</nome>
        <stato>Disabilitata</stato>
        <listaAzioni>
            <azioneUtente>
                <nomeAzione>Registrazione cliente</nomeAzione>
            </azioneUtente>
        </listaAzioni>        
        <listaUtenti>
            <utente>
                <codFisc>RSSGNN64R03E472G</codFisc>
            </utente>
            <utente>
                <codFisc>VRDRRT00L13E472M</codFisc>
            </utente>
            <utente>
                <codFisc>CPZGLC90P11H501W</codFisc>
            </utente>
            <utente>
                <codFisc>BRSMTT64E05E472K</codFisc>
            </utente>
            <utente>
                <codFisc>BNCVNT00R67E472F</codFisc>
            </utente>
        </listaUtenti>
    </categoria>
</listaCategorie>
