=== AngeloTrifelli/Tesina-LWEB/XML/Clienti.xsd
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaClienti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="cliente" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="cliente">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="cognome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="dataDiNascita" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="indirizzo" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="telefono" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="email" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="numeroCarta" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="credenziali" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="crediti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="dataAssegnazioneCrediti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="sommaGiudizi" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="codFisc" type="xsd:ID"  use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nome" type="xsd:string" />
    <xsd:element name="cognome" type="xsd:string" />
    <xsd:element name="dataDiNascita" type="xsd:date" />
    <xsd:element name="indirizzo" type="xsd:string" />
    <xsd:element name="telefono">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:pattern value="[0-9]{10}" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="email" type="xsd:string" />
    <xsd:element name="numeroCarta">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:pattern value="[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="credenziali">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="username" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="password" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="username" type="xsd:string" />
    <xsd:element name="password" type="xsd:string" />
    <xsd:element name="crediti">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="dataAssegnazioneCrediti" type="xsd:date" />
    <xsd:element name="sommaGiudizi">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
</xsd:schema>
=======
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaClienti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="cliente" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="cliente">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="cognome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="dataDiNascita" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="indirizzo" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="telefono" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="email" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="numeroCarta" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="credenziali" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="crediti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="dataAssegnazioneCrediti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="sommaGiudizi" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="codFisc" type="xsd:ID"  use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nome" type="xsd:string" />
    <xsd:element name="cognome" type="xsd:string" />
    <xsd:element name="dataDiNascita" type="xsd:date" />
    <xsd:element name="indirizzo" type="xsd:string" />
    <xsd:element name="telefono">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:pattern value="[0-9]{10}" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="email" type="xsd:string" />
    <xsd:element name="numeroCarta">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:pattern value="[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="credenziali">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="username" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="password" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="username" type="xsd:string" />
    <xsd:element name="password" type="xsd:string" />
    <xsd:element name="crediti">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="dataAssegnazioneCrediti" type="xsd:date" />
    <xsd:element name="sommaGiudizi">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
</xsd:schema>
>>>>>>> master

=== AngeloTrifelli/Tesina-LWEB/XML/Clienti.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaClienti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Clienti.xsd">
  <cliente codFisc="RSSGNN64R03E472G">
    <nome>Giovanni</nome>
    <cognome>Rossi</cognome>
    <dataDiNascita>1964-10-03</dataDiNascita>
    <indirizzo>via del quasimodo 7</indirizzo>
    <telefono>0123456789</telefono>
    <email>giovanni.rossi64@gmail.com</email>
    <numeroCarta>0000-0000-0000-0000</numeroCarta>
    <credenziali>
      <username>GiovanniRossi</username>
      <password>d8578edf8458ce06fbc5bb76a58c5ca4</password>
    </credenziali>
    <crediti>0</crediti>
    <dataAssegnazioneCrediti>2022-10-03</dataAssegnazioneCrediti>
    <sommaGiudizi>0</sommaGiudizi>
  </cliente>
  <cliente codFisc="VRDRRT00L13E472M">
    <nome>Roberto</nome>
    <cognome>Verdi</cognome>
    <dataDiNascita>2000-07-13</dataDiNascita>
    <indirizzo>via della stazione 112</indirizzo>
    <telefono>9876543210</telefono>
    <email>roberto.verdi00@gmail.com</email>
    <numeroCarta>1111-1111-1111-1111</numeroCarta>
    <credenziali>
      <username>RobertoVerdi</username>
      <password>81dc9bdb52d04dc20036dbd8313ed055</password>
    </credenziali>
    <crediti>0</crediti>
    <dataAssegnazioneCrediti>2022-02-01</dataAssegnazioneCrediti>
    <sommaGiudizi>0</sommaGiudizi>
  </cliente>
  <cliente codFisc="CPZGLC90P11H501W">
    <nome>Gianluca</nome>
    <cognome>Capozzi</cognome>
    <dataDiNascita>1990-09-11</dataDiNascita>
    <indirizzo>via delle baldorie 18</indirizzo>
    <telefono>3472299220</telefono>
    <email>gianluca.capozzi@gmail.com</email>
    <numeroCarta>4545-5454-4545-5454</numeroCarta>
    <credenziali>
      <username>GianlucaCapozzi90</username>
      <password>9180151f16931b45f176374a1105f838</password>
    </credenziali>
    <crediti>0</crediti>
    <dataAssegnazioneCrediti>2022-10-03</dataAssegnazioneCrediti>
    <sommaGiudizi>0</sommaGiudizi>
  </cliente>
  <cliente codFisc="BNCVNT00R67E472F">
    <nome>Valentina</nome>
    <cognome>Bianchi</cognome>
    <dataDiNascita>2000-10-27</dataDiNascita>
    <indirizzo>via delle camelie 89</indirizzo>
    <telefono>3886868689</telefono>
    <email>valentina.bianchi@gmail.com</email>
    <numeroCarta>1313-1313-1213-1212</numeroCarta>
    <credenziali>
      <username>ValeBianchi</username>
      <password>dc4c436406376b6a492e6e8e65e5a367</password>
    </credenziali>
    <crediti>0</crediti>
    <dataAssegnazioneCrediti>2022-10-03</dataAssegnazioneCrediti>
    <sommaGiudizi>0</sommaGiudizi>
  </cliente>
  <cliente codFisc="BRSMTT64E05E472K">
    <nome>Matteo</nome>
    <cognome>Briscola</cognome>
    <dataDiNascita>1964-05-05</dataDiNascita>
    <indirizzo>Via pericle 90</indirizzo>
    <telefono>3493434345</telefono>
    <email>matteo.briscola@gmail.com</email>
    <numeroCarta>1232-4545-3468-8634</numeroCarta>
    <credenziali>
      <username>MatteBrisco</username>
      <password>235dafa09887d5fef4700f7c9c3ec588</password>
    </credenziali>
    <crediti>0</crediti>
    <dataAssegnazioneCrediti>2022-10-03</dataAssegnazioneCrediti>
    <sommaGiudizi>0</sommaGiudizi>
  </cliente>
</listaClienti>
