=== AngeloTrifelli/Tesina-LWEB/XML/Commenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaCommenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="commento" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="commento">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="idRecensione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="nomeAutore" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="cognomeAutore" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="codFiscAutore" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="testo" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="utilita" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="accordo" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="listaRisposte" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:ID" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="idRecensione" type="xsd:string" />
    <xsd:element name="nomeAutore" type="xsd:string" />
    <xsd:element name="cognomeAutore" type="xsd:string" />
    <xsd:element name="codFiscAutore" type="xsd:string" />
    <xsd:element name="testo" type="xsd:string" />
    
    <xsd:element name="utilita">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="accordo">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="listaRisposte">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="risposta" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="risposta">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="idRisposta" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="nomeAutoreRisposta" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="cognomeAutoreRisposta" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="codFiscAutoreRisposta" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="testoRisposta" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="utilitaRisposta" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="accordoRisposta" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="idRisposta" type="xsd:ID" />
    <xsd:element name="nomeAutoreRisposta" type="xsd:string" />
    <xsd:element name="cognomeAutoreRisposta" type="xsd:string" />
    <xsd:element name="codFiscAutoreRisposta" type="xsd:string" />
    <xsd:element name="testoRisposta" type="xsd:string" />

    <xsd:element name="utilitaRisposta">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="accordoRisposta">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

</xsd:schema>

=== AngeloTrifelli/Tesina-LWEB/XML/Commenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaCommenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Commenti.xsd">
  <commento id="CM1">
    <idRecensione>R1</idRecensione>
    <nomeAutore>Roberto</nomeAutore>
    <cognomeAutore>Verdi</cognomeAutore>
    <codFiscAutore>VRDRRT00L13E472M</codFiscAutore>
    <testo>Concordo pienamente!</testo>
    <utilita>0</utilita>
    <accordo>0</accordo>
    <listaRisposte/>
  </commento>
  <commento id="CM2">
    <idRecensione>R2</idRecensione>
    <nomeAutore>Valentina</nomeAutore>
    <cognomeAutore>Bianchi</cognomeAutore>
    <codFiscAutore>BNCVNT00R67E472F</codFiscAutore>
    <testo>Volevo prenotare proprio una suite oggi, ma sto cambiando idea. Senza l'idromassaggio non conviene.</testo>
    <utilita>0</utilita>
    <accordo>6</accordo>
    <listaRisposte>
      <risposta>
        <idRisposta>CM2-CMR1</idRisposta>
        <nomeAutoreRisposta>Roberto</nomeAutoreRisposta>
        <cognomeAutoreRisposta>Verdi</cognomeAutoreRisposta>
        <codFiscAutoreRisposta>VRDRRT00L13E472M</codFiscAutoreRisposta>
        <testoRisposta>Tranquilla Valentina, l'idromassaggio è stato sistemato pochi giorni dopo.</testoRisposta>
        <utilitaRisposta>5</utilitaRisposta>
        <accordoRisposta>0</accordoRisposta>
      </risposta>
      <risposta>
        <idRisposta>CM2-CMR2</idRisposta>
        <nomeAutoreRisposta>Valentina</nomeAutoreRisposta>
        <cognomeAutoreRisposta>Bianchi</cognomeAutoreRisposta>
        <codFiscAutoreRisposta>BNCVNT00R67E472F</codFiscAutoreRisposta>
        <testoRisposta>Ah menomale, mi stavo preoccupando. Grazie mille per l'informazione.</testoRisposta>
        <utilitaRisposta>0</utilitaRisposta>
        <accordoRisposta>0</accordoRisposta>
      </risposta>
      <risposta>
        <idRisposta>CM2-CMR3</idRisposta>
        <nomeAutoreRisposta>Roberto</nomeAutoreRisposta>
        <cognomeAutoreRisposta>Verdi</cognomeAutoreRisposta>
        <codFiscAutoreRisposta>VRDRRT00L13E472M</codFiscAutoreRisposta>
        <testoRisposta>Di nulla!</testoRisposta>
        <utilitaRisposta>0</utilitaRisposta>
        <accordoRisposta>0</accordoRisposta>
      </risposta>
    </listaRisposte>
  </commento>
  <commento id="CM3">
    <idRecensione>R3</idRecensione>
    <nomeAutore>Roberto</nomeAutore>
    <cognomeAutore>Verdi</cognomeAutore>
    <codFiscAutore>VRDRRT00L13E472M</codFiscAutore>
    <testo>Non posso essere più d'accordo, credo sia l'unico hotel che lo faccia.</testo>
    <utilita>0</utilita>
    <accordo>0</accordo>
    <listaRisposte>
      <risposta>
        <idRisposta>CM3-CMR1</idRisposta>
        <nomeAutoreRisposta>Giovanni</nomeAutoreRisposta>
        <cognomeAutoreRisposta>Rossi</cognomeAutoreRisposta>
        <codFiscAutoreRisposta>RSSGNN64R03E472G</codFiscAutoreRisposta>
        <testoRisposta>Che idea pazzesca!</testoRisposta>
        <utilitaRisposta>0</utilitaRisposta>
        <accordoRisposta>0</accordoRisposta>
      </risposta>
    </listaRisposte>
  </commento>
</listaCommenti>
