=== AngeloTrifelli/Tesina-LWEB/XML/Recensioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaRecensioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="recensione" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="recensione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nomeAutore" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="cognomeAutore" minOccurs="1"  maxOccurs="1" />
                <xsd:element ref="codFiscAutore" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="categoria" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="testoRecensione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="voto" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="utilita" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="accordo" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:ID" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nomeAutore" type="xsd:string" />
    <xsd:element name="cognomeAutore" type="xsd:string" />
    <xsd:element name="codFiscAutore" type="xsd:string" />
    <xsd:element name="categoria" type="xsd:string" />
    <xsd:element name="testoRecensione" type="xsd:string" />
    <xsd:element name="voto">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="1" />
                <xsd:maxInclusive value="5" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="utilita">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="accordo">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
</xsd:schema>

=== AngeloTrifelli/Tesina-LWEB/XML/Recensioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaRecensioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Recensioni.xsd">
    <recensione id="R1">
        <nomeAutore>Giovanni</nomeAutore>
        <cognomeAutore>Rossi</cognomeAutore>
        <codFiscAutore>RSSGNN64R03E472G</codFiscAutore>
        <categoria>Servizi</categoria>
        <testoRecensione>
            Soggiorno fantastico! Il ristorante offre sempre piatti di immensa qualità ed il personale è 
            estremamente professionale e sempre disponibile. 
        </testoRecensione>
        <voto>5</voto>
        <utilita>0</utilita>
        <accordo>0</accordo>
    </recensione>
    <recensione id="R2">
        <nomeAutore>Roberto</nomeAutore>
        <cognomeAutore>Verdi</cognomeAutore>
        <codFiscAutore>VRDRRT00L13E472M</codFiscAutore>
        <categoria>Generale</categoria>
        <testoRecensione>
            Ho alloggiato nell'hotel la notte del 17 settembre, camera Suite. La camera eccezionale, costa risetto le altre ma è di tutt'altro livello, per questo ne vale la pena.
            Unica pecca è l'idromassaggio, non vedevo l'ora di provarlo ma durante il mio soggiorno era in manutenzione, e non mi è stato fatto neanche uno sconto sulla camera. Per questo do 3 stelle.
        </testoRecensione>
        <voto>3</voto>
        <utilita>0</utilita>
        <accordo>0</accordo>
    </recensione>
    <recensione id="R3">
        <nomeAutore>Matteo</nomeAutore>
        <cognomeAutore>Briscola</cognomeAutore>
        <codFiscAutore>BRSMTT64E05E472K</codFiscAutore>
        <categoria>Crediti</categoria>
        <testoRecensione>
            Fantastica questa funnzione dei crediti, ho risparmiato tantissimo sul mio prossimo soggiorno. 5 stelle piene!
        </testoRecensione>
        <voto>5</voto>
        <utilita>0</utilita>
        <accordo>0</accordo>
    </recensione>
</listaRecensioni>
