=== AngeloTrifelli/Tesina-LWEB/XML/ServizioCamera.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaPrenotazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:sequence>
                    <xsd:element ref="prenotazione" minOccurs="0" maxOccurs="unbounded" />
                </xsd:sequence>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prenotazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="codFisc" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="data" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="ora" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="richieste" minOccurs="0" maxOccurs="1" />
                <xsd:element ref="prezzoTotale" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="creditiUsati" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="listaPortate" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:ID" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="codFisc" type="xsd:string" />
    <xsd:element name="data" type="xsd:date" />
    <xsd:element name="ora" type="xsd:time" />
    <xsd:element name="richieste" type="xsd:string" />
    <xsd:element name="prezzoTotale">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minExclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="creditiUsati">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="listaPortate">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="portata" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="portata">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="quantita" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nome" type="xsd:string" />
    <xsd:element name="quantita">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="1" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
</xsd:schema>

=== AngeloTrifelli/Tesina-LWEB/XML/ServizioCamera.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaPrenotazioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ServizioCamera.xsd">
  <prenotazione id="PSC1">
    <codFisc>RSSGNN64R03E472G</codFisc>
    <data>2022-06-14</data>
    <ora>20:30:00</ora>
    <richieste/>
    <prezzoTotale>26</prezzoTotale>
    <creditiUsati>0</creditiUsati>
    <listaPortate>
      <portata>
        <nome>Antipasto di montagna</nome>
        <prezzo>9</prezzo>
        <quantita>1</quantita>
      </portata>
      <portata>
        <nome>Tagliata di manzo</nome>
        <prezzo>15</prezzo>
        <quantita>1</quantita>
      </portata>
      <portata>
        <nome>Sorbetto al limone</nome>
        <prezzo>2</prezzo>
        <quantita>1</quantita>
      </portata>
    </listaPortate>
  </prenotazione>
  <prenotazione id="PSC2">
    <codFisc>RSSGNN64R03E472G</codFisc>
    <data>2022-10-28</data>
    <ora>22:00:00</ora>
    <richieste>BUSSARE PRIMA DI ENTRARE</richieste>
    <prezzoTotale>42</prezzoTotale>
    <creditiUsati>0</creditiUsati>
    <listaPortate>
      <portata>
        <nome>Spaghetti alla carbonara</nome>
        <prezzo>8</prezzo>
        <quantita>2</quantita>
      </portata>
      <portata>
        <nome>Grigliata mista</nome>
        <prezzo>20</prezzo>
        <quantita>1</quantita>
      </portata>
      <portata>
        <nome>Tiramisu</nome>
        <prezzo>3</prezzo>
        <quantita>2</quantita>
      </portata>
    </listaPortate>
  </prenotazione>
  <prenotazione id="PSC3">
    <codFisc>CPZGLC90P11H501W</codFisc>
    <data>2022-11-12</data>
    <ora>20:00:00</ora>
    <richieste/>
    <prezzoTotale>31</prezzoTotale>
    <creditiUsati>0</creditiUsati>
    <listaPortate>
      <portata>
        <nome>Antipasto di montagna</nome>
        <prezzo>8</prezzo>
        <quantita>1</quantita>
      </portata>
      <portata>
        <nome>Lasagne</nome>
        <prezzo>9</prezzo>
        <quantita>2</quantita>
      </portata>
      <portata>
        <nome>Sorbetto al limone</nome>
        <prezzo>2</prezzo>
        <quantita>1</quantita>
      </portata>
      <portata>
        <nome>Tiramisu</nome>
        <prezzo>3</prezzo>
        <quantita>1</quantita>
      </portata>
    </listaPortate>
  </prenotazione>
</listaPrenotazioni>
