=== AngeloTrifelli/Tesina-LWEB/XML/Tavoli.xsd
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaTavoli">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tavolo" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="tavolo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="locazione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="listaPrenotazioni" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="numero" type="xsd:ID" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="locazione">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Interna" />
                <xsd:enumeration value="Esterna" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    
    <xsd:element name="listaPrenotazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prenotazione" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prenotazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="idPrenotazione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="codFisc" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="data" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="ora" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="idPrenotazione" type="xsd:ID" />
    <xsd:element name="codFisc" type="xsd:string" />
    <xsd:element name="data" type="xsd:date" />
    <xsd:element name="ora" type="xsd:time" />
=======
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaTavoli">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tavolo" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="tavolo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="locazione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="listaPrenotazioni" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="numero" type="xsd:ID" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="locazione">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Interna" />
                <xsd:enumeration value="Esterna" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    
    <xsd:element name="listaPrenotazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prenotazione" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="prenotazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="idPrenotazione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="codFisc" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="data" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="ora" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="idPrenotazione" type="xsd:ID" />
    <xsd:element name="codFisc" type="xsd:string" />
    <xsd:element name="data" type="xsd:date" />
    <xsd:element name="ora" type="xsd:time" />
>>>>>>> master
</xsd:schema>

=== AngeloTrifelli/Tesina-LWEB/XML/Tavoli.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaTavoli xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Tavoli.xsd">
    <tavolo numero="T2">
        <locazione>Interna</locazione>
        <listaPrenotazioni>
            <prenotazione>
                <idPrenotazione>T2-PT1</idPrenotazione>
                <codFisc>RSSGNN64R03E472G</codFisc>
                <data>2022-10-30</data>
                <ora>21:30:00</ora>
            </prenotazione>
        </listaPrenotazioni>
    </tavolo>
</listaTavoli>
