=== AngeloTrifelli/Tesina-LWEB/XML/Valutazioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listaValutazioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="valutazione" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="valutazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="idOggettoValutato" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="codFisc" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="votoUtilita" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="votoAccordo" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="idOggettoValutato" type="xsd:string" />
    <xsd:element name="codFisc" type="xsd:string" />

    <xsd:element name="votoUtilita">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
                <xsd:maxInclusive value="5" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="votoAccordo">
        <xsd:simpleType>
            <xsd:restriction base="xsd:int">
                <xsd:minInclusive value="0" />
                <xsd:maxInclusive value="3" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
</xsd:schema>

=== AngeloTrifelli/Tesina-LWEB/XML/Valutazioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaValutazioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Valutazioni.xsd">
  <valutazione>
    <idOggettoValutato>R3</idOggettoValutato>
    <codFisc>CPZGLC90P11H501W</codFisc>
    <votoUtilita>0</votoUtilita>
    <votoAccordo>3</votoAccordo>
  </valutazione>
  <valutazione>
    <idOggettoValutato>CM2-CMR1</idOggettoValutato>
    <codFisc>CPZGLC90P11H501W</codFisc>
    <votoUtilita>5</votoUtilita>
    <votoAccordo>0</votoAccordo>
  </valutazione>
  <valutazione>
    <idOggettoValutato>CM2</idOggettoValutato>
    <codFisc>CPZGLC90P11H501W</codFisc>
    <votoUtilita>0</votoUtilita>
    <votoAccordo>3</votoAccordo>
  </valutazione>
  <valutazione>
    <idOggettoValutato>R1</idOggettoValutato>
    <codFisc>CPZGLC90P11H501W</codFisc>
    <votoUtilita>3</votoUtilita>
    <votoAccordo>3</votoAccordo>
  </valutazione>
  <valutazione>
    <idOggettoValutato>R3</idOggettoValutato>
    <codFisc>RSSGNN64R03E472G</codFisc>
    <votoUtilita>0</votoUtilita>
    <votoAccordo>3</votoAccordo>
  </valutazione>
  <valutazione>
    <idOggettoValutato>R2</idOggettoValutato>
    <codFisc>RSSGNN64R03E472G</codFisc>
    <votoUtilita>5</votoUtilita>
    <votoAccordo>0</votoAccordo>
  </valutazione>
  <valutazione>
    <idOggettoValutato>CM2</idOggettoValutato>
    <codFisc>RSSGNN64R03E472G</codFisc>
    <votoUtilita>0</votoUtilita>
    <votoAccordo>3</votoAccordo>
  </valutazione>
</listaValutazioni>
